language: ruby
env:
  global:
    - WAD_S3_BUCKET_NAME=travis-wad
    - WAD_S3_REGION=us-west-2
    - secure: JN2mfVHbKBmqYSWCUanSyKS4TfDxRdBIkkdKgww58uvUVrgnYKzGlV+T0KQrx8GoAG32H/S3C9gFwOYs7Zh/M7a74IPNaXiQmPvON4Ao1xYSpgNpVeFai4EK1342shLCLxu5v9xdKnddBFQ15m6xH0TCByTqcEz66fgkjFzhi9A=
    - secure: cjx/dR9jqO9mkaFMK/5I3A2cD7DU/PebidQDJMjukAKRoRIM7YvL7oneFJCuYXj0XfuXSi1k+92A++msLEyZnI0cTuQ8HcDMoZQI89m88mvkxwxADy57M2w3DdQfrLtWMBVT6xxykHpddltKM4ABYW1/zOy9A0t3ABFbrLjgKYQ=
rvm:
  - 2.1.3
install: "travis_retry bin/wad"
before_script:
  - bundle exec rake db:create db:structure:load
script: bundle exec rake test:all
#after_success:
#  - 'echo -e "Host 107.170.189.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
#  - ssh root@107.170.189.56 "/var/hummingbird/deploy.sh"
notifications:
  hipchat:
    rooms:
      secure: aXpt7vF8j08UA48UltX9BOd5PjaSp8EG6lcKtjM6oi2K0EF+NlJq3RZRKgrYbNTISbOjJUJlFdbGG8oUBi0ilZV0kvF2JYlB16HZgUEcsSeTInUEmPZoy+VvgTve/L+b4+2cgC0pyxC6kzCk9PAYQ3ZCsqSbwISZmHV4cG1k9tg=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
