- name: Create Capistrano directory structure
  file: path=$item state=directory recurse=false owner=vikhyat mode=0755
  with_items:
  - /u/apps/hummingbird
  - /u/apps/hummingbird/releases
  - /u/apps/hummingbird/shared
  - /u/apps/hummingbird/shared/log
  - /u/apps/hummingbird/shared/pids
  - /u/apps/hummingbird/shared/system

- name: Install important packages
  apt: pkg=$item state=present
  with_items:
  - vim
  - ntp

- name: Create .ssh directory
  file: path=/home/vikhyat/.ssh state=directory owner=vikhyat

- name: Copy over env
  template: dest=/etc/profile.d/env.sh src=env.j2 owner=root group=root mode=0755

- name: Copy over AWS credentials
  copy: dest=/etc/profile.d/aws.sh src=../aws_env owner=root group=root mode=0755

- name: Set timezone to UTC
  lineinfile: dest=/etc/timezone state=present insertbefore=BOF
              regexp="^Etc/UTC" line="Etc/UTC"
  register: timezone

- name: Reconfigure tzdata
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed

- name: Copy SSH stuff
  copy: dest=/home/vikhyat/.ssh/$item src=$item
  with_items:
  - id_rsa
  - id_rsa.pub

- name: Install python-software-properties.
  action: apt pkg=python-software-properties state=present

- include: iptables.yml
#- include: rbenv.yml
- include: newrelic.yml

- name: Install monit
  action: apt pkg=monit state=present

- name: Copy monit config
  action: copy src=monitrc dest=/etc/monit/monitrc

- name: Add Postgres Apt signing key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Copy Postgres repository source file
  template: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list

- name: Install libpq
  apt: pkg=$item state=present update_cache=yes
  with_items:
  - libpq-dev
  - libpq5
